### EDA on Kaggle

- https://www.kaggle.com/vanguarde/h-m-eda-first-look
- https://www.kaggle.com/gpreda/h-m-eda-and-prediction
- https://www.kaggle.com/remekkinas/h-m-eda-first-look-into-data
- https://www.kaggle.com/vickeytomer/h-m-eda-exploration
- https://www.kaggle.com/negoto/best-selling-items-catalog-like-eda-of-articles

In [1]:
import pandas as pd

## 1. transactions_train.csv

In [2]:
%%time
#read transaction.csv
transaction_raw = pd.read_csv("../data/large_data/transactions_train.csv")

Wall time: 21.4 s

In [3]:
transaction_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31788324 entries, 0 to 31788323
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   t_dat             object
 1   customer_id       object
 2   article_id        int64
 3   price             float64
 4   sales_channel_id  int64
dtypes: float64(1), int64(2), object(2)
memory usage: 1.2+ GB

In [4]:
transaction_raw.head()

,t_dat,customer_id,article_id,price,sales_channel_id
0,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,663713001,0.050831,2
1,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,541518023,0.030492,2
2,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,505221004,0.015237,2
3,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687003,0.016932,2
4,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687004,0.016932,2

In [5]:
#check start date and last date
print("Start date:", transaction_raw.t_dat.min())
print("Last date:", transaction_raw.t_dat.max())

Start date: 2018-09-20
Last date: 2020-09-22

In [6]:
#Convert t_dat to datetime 
transaction_raw['t_dat'] = pd.to_datetime(transaction_raw['t_dat'])

In [7]:
#add year, month, and week column
transaction_raw['year'] = transaction_raw['t_dat'].dt.isocalendar().year
transaction_raw['month'] = transaction_raw['t_dat'].dt.month
transaction_raw['week'] = transaction_raw['t_dat'].dt.isocalendar().week

In [8]:
transaction_raw.head()

,t_dat,customer_id,article_id,price,sales_channel_id,year,month,week
0,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,663713001,0.050831,2,2018,9,38
1,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,541518023,0.030492,2,2018,9,38
2,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,505221004,0.015237,2,2018,9,38
3,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687003,0.016932,2,2018,9,38
4,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687004,0.016932,2,2018,9,38

In [9]:
#count number of transactions for each year
transaction_raw.year.value_counts()

2019    16361525
2020    11039440
2018     4387359
Name: year, dtype: Int64

In [10]:
#count number of transactions for each month
transaction_raw.month.value_counts()

6     3670709
7     3158996
5     2922134
4     2817336
9     2620223
10    2543812
8     2490722
11    2468652
1     2339825
3     2334502
12    2267142
2     2154271
Name: month, dtype: int64

In [11]:
#Extract 2019 Summer (5,6,7) data
mask = (transaction_raw.year == 2019) & (transaction_raw.month >= 5) & (transaction_raw.month <= 7)
transaction_2019_summer = transaction_raw.loc[mask]
transaction_2019_summer

,t_dat,customer_id,article_id,price,sales_channel_id,year,month,week
9590349,2019-05-01,00019d6c20e0fbb551af18c57149af4707ec016bb0decd...,524061003,0.050831,2,2019,5,18
9590350,2019-05-01,00019d6c20e0fbb551af18c57149af4707ec016bb0decd...,735404001,0.050831,2,2019,5,18
9590351,2019-05-01,00019d6c20e0fbb551af18c57149af4707ec016bb0decd...,700370004,0.016932,2,2019,5,18
9590352,2019-05-01,00019d6c20e0fbb551af18c57149af4707ec016bb0decd...,618800001,0.033881,2,2019,5,18
9590353,2019-05-01,00019d6c20e0fbb551af18c57149af4707ec016bb0decd...,731407001,0.016932,2,2019,5,18
...,...,...,...,...,...,...,...,...
14864359,2019-07-31,ffdb44f83b6d23c1c9f805f5084392db7d4ff850df1373...,751989001,0.025407,2,2019,7,31
14864360,2019-07-31,ffe4bd3f42225fb51da4fe110a0fb2519efef670ff07ee...,757811001,0.013542,1,2019,7,31
14864361,2019-07-31,ffe4bd3f42225fb51da4fe110a0fb2519efef670ff07ee...,806388002,0.006763,1,2019,7,31
14864362,2019-07-31,fff221aba935ab52c5aeda592994e298c8170b2656b0e5...,759231002,0.059305,2,2019,7,31
14864363,2019-07-31,fff221aba935ab52c5aeda592994e298c8170b2656b0e5...,706637001,0.024390,2,2019,7,31

In [12]:
#check the week number in 2019 summer data
transaction_2019_summer.week.unique()

<IntegerArray>
[18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
Length: 14, dtype: UInt32

In [13]:
#count number of transaction each week
transaction_2019_summer.week.value_counts()

26    562990
25    560076
30    471866
27    429526
22    407801
28    374637
29    371077
21    357346
20    340916
23    335091
24    327337
18    291779
19    283185
31    160388
Name: week, dtype: Int64

## 2. articles.csv

In [14]:
%%time

article_raw = pd.read_csv("../data/large_data/articles.csv")

Wall time: 390 ms

In [15]:
article_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105542 entries, 0 to 105541
Data columns (total 25 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   article_id                    105542 non-null  int64
 1   product_code                  105542 non-null  int64
 2   prod_name                     105542 non-null  object
 3   product_type_no               105542 non-null  int64
 4   product_type_name             105542 non-null  object
 5   product_group_name            105542 non-null  object
 6   graphical_appearance_no       105542 non-null  int64
 7   graphical_appearance_name     105542 non-null  object
 8   colour_group_code             105542 non-null  int64
 9   colour_group_name             105542 non-null  object
 10  perceived_colour_value_id     105542 non-null  int64
 11  perceived_colour_value_name   105542 non-null  object
 12  perceived_colour_master_id    105542 non-null  int64
 13  perceived_colour_master_name  105542 non-null  object
 14  department_no                 105542 non-null  int64
 15  department_name               105542 non-null  object
 16  index_code                    105542 non-null  object
 17  index_name                    105542 non-null  object
 18  index_group_no                105542 non-null  int64
 19  index_group_name              105542 non-null  object
 20  section_no                    105542 non-null  int64
 21  section_name                  105542 non-null  object
 22  garment_group_no              105542 non-null  int64
 23  garment_group_name            105542 non-null  object
 24  detail_desc                   105126 non-null  object
dtypes: int64(11), object(14)
memory usage: 20.1+ MB

In [16]:
article_raw

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,108775051,108775,Strap top (1),253,Vest top,Garment Upper body,1010017,Stripe,11,Off White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
3,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
4,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105537,953450001,953450,5pk regular Placement1,302,Socks,Socks & Tights,1010014,Placement print,9,Black,...,Socks Bin,F,Menswear,3,Menswear,26,Men Underwear,1021,Socks and Tights,Socks in a fine-knit cotton blend with a small...
105538,953763001,953763,SPORT Malaga tank,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey,A,Ladieswear,1,Ladieswear,2,H&M+,1005,Jersey Fancy,Loose-fitting sports vest top in ribbed fast-d...
105539,956217002,956217,Cartwheel dress,265,Dress,Garment Full body,1010016,Solid,9,Black,...,Jersey,A,Ladieswear,1,Ladieswear,18,Womens Trend,1005,Jersey Fancy,"Short, A-line dress in jersey with a round nec..."
105540,957375001,957375,CLAIRE HAIR CLAW,72,Hair clip,Accessories,1010016,Solid,9,Black,...,Small Accessories,D,Divided,2,Divided,52,Divided Accessories,1019,Accessories,Large plastic hair claw.
105541,959461001,959461,Lounge dress,265,Dress,Garment Full body,1010016,Solid,11,Off White,...,Jersey,A,Ladieswear,1,Ladieswear,18,Womens Trend,1005,Jersey Fancy,Calf-length dress in ribbed jersey made from a...

In [17]:
#merge 2019 summer transactions and article csv
transaction_2019summer_articles = pd.merge(transaction_2019_summer, article_raw, on="article_id", how="left")

In [18]:
transaction_2019summer_articles

,t_dat,customer_id,article_id,price,sales_channel_id,year,month,week,product_code,prod_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,2019-05-01,00019d6c20e0fbb551af18c57149af4707ec016bb0decd...,524061003,0.050831,2,2019,5,18,524061,s,...,Denim Other Garments,D,Divided,2,Divided,57,Ladies Denim,1016,Trousers Denim,Short 5-pocket skirt in washed stretch denim w...
1,2019-05-01,00019d6c20e0fbb551af18c57149af4707ec016bb0decd...,735404001,0.050831,2,2019,5,18,735404,Melrose,...,Dress,A,Ladieswear,1,Ladieswear,15,Womens Everyday Collection,1013,Dresses Ladies,"Calf-length, V-neck dress in woven fabric with..."
2,2019-05-01,00019d6c20e0fbb551af18c57149af4707ec016bb0decd...,700370004,0.016932,2,2019,5,18,700370,Cash Padded Balconette,...,Expressive Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Lace balconette bra with moulded, lightly padd..."
3,2019-05-01,00019d6c20e0fbb551af18c57149af4707ec016bb0decd...,618800001,0.033881,2,2019,5,18,618800,Leona,...,Blouse,A,Ladieswear,1,Ladieswear,15,Womens Everyday Collection,1010,Blouses,V-neck satin top with a lace trim at the top a...
4,2019-05-01,00019d6c20e0fbb551af18c57149af4707ec016bb0decd...,731407001,0.016932,2,2019,5,18,731407,Macarena,...,Blouse,A,Ladieswear,1,Ladieswear,15,Womens Everyday Collection,1010,Blouses,Top in a crinkled viscose weave with a V-neck ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5274010,2019-07-31,ffdb44f83b6d23c1c9f805f5084392db7d4ff850df1373...,751989001,0.025407,2,2019,7,31,751989,Lace body,...,Jersey Fancy DS,D,Divided,2,Divided,58,Divided Selected,1005,Jersey Fancy,Wrapover body in cotton jersey with lace trims...
5274011,2019-07-31,ffe4bd3f42225fb51da4fe110a0fb2519efef670ff07ee...,757811001,0.013542,1,2019,7,31,757811,Barry Tee,...,Jersey Fancy,F,Menswear,3,Menswear,55,Contemporary Street,1005,Jersey Fancy,T-shirt in cotton jersey with a ribbed neckline.
5274012,2019-07-31,ffe4bd3f42225fb51da4fe110a0fb2519efef670ff07ee...,806388002,0.006763,1,2019,7,31,806388,Therese tee,...,Basic 1,D,Divided,2,Divided,51,Divided Basics,1002,Jersey Basic,Wide T-shirt in soft cotton jersey with a ribb...
5274013,2019-07-31,fff221aba935ab52c5aeda592994e298c8170b2656b0e5...,759231002,0.059305,2,2019,7,31,759231,Amalfi,...,Dress,A,Ladieswear,1,Ladieswear,15,Womens Everyday Collection,1013,Dresses Ladies,"Maxi dress in a striped weave with a wide, ela..."
5274014,2019-07-31,fff221aba935ab52c5aeda592994e298c8170b2656b0e5...,706637001,0.024390,2,2019,7,31,706637,Lyon dress,...,Dress,A,Ladieswear,1,Ladieswear,6,Womens Casual,1013,Dresses Ladies,"Knee-length, off-the-shoulder dress in a plume..."

In [19]:
transaction_2019summer_articles.index_group_name.value_counts()

Ladieswear       3554714
Divided          1146719
Menswear          286347
Sport             157728
Baby/Children     128507
Name: index_group_name, dtype: int64

In [20]:
customer_buy_group = transaction_2019summer_articles.groupby('customer_id')['index_group_name'].unique()
customer_buy_group

customer_id
00000dbacae5abe5e23885899a1fa44253a17956c6d1c3d25f88aa139fdfc657    [Baby/Children, Ladieswear, Divided]
0000423b00ade91418cceaf3b26c6af3dd342b51fd051eec9c12fb36984420fa                   [Divided, Ladieswear]
00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2c5feb1ca5dff07c43e                                 [Sport]
0000757967448a6cb83efb3ea7a3fb9d418ac7adf2379d8cd0c725276a467a2a                            [Ladieswear]
00007d2de826758b65a93dd24ce629ed66842531df6699338c5570910a014cc2                   [Ladieswear, Divided]
                                                                                    ...
ffff61677073258d461e043cc9ed4ed97be5617a920640ff61024f4619bf41c4                            [Ladieswear]
ffff8f9ecdce722b5bab97fff68a6d1866492209bfe5242c50d2a10a652fb5ef                            [Ladieswear]
ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e4747568cac33e8c541831                            [Ladieswear]
ffffcd5046a6143d29a04fb8c424ce494a76e5cdf4fab53481233731b5c4f8b7                     [Divided, Menswear]
ffffcf35913a0bee60e8741cb2b4e78b8a98ee5ff2e6a1778d0116cffd259264                               [Divided]
Name: index_group_name, Length: 559625, dtype: object

## Check among customers who bought Menswear items also bought what other category

In [21]:
index_group_count = {'Menswear':0, 'Ladieswear':0, 'Divided':0, 'Sport':0, 'Baby/Children': 0}
for cid, groups in customer_buy_group.items():
    if 'Menswear' in groups:
        for group_name in list(groups):
            index_group_count[group_name] += 1
index_group_count

{'Menswear': 80081,
 'Ladieswear': 66738,
 'Divided': 46923,
 'Sport': 11808,
 'Baby/Children': 9427}

### Check _name info (2019 Summer)

In [21]:
#prod_name
transaction_2019summer_articles.prod_name.value_counts()

Kelso HW fancy                  26910
Simple as That Triangle Top     22094
Timeless Midrise Brief          22025
Simple as that Cheeky Tanga     21252
Shake it in Balconette          18333
                                ...
MIGHETTO scarf                      1
Swift lace and chiffon dress        1
CNY BASIC HOOD                      1
Class dollarstone earringpk         1
Moonlight Padded T-shirt            1
Name: prod_name, Length: 21752, dtype: int64

In [22]:
#product_type_name
transaction_2019summer_articles.product_type_name.value_counts()

Dress          664385
Trousers       509601
Shorts         435173
T-shirt        426080
Vest top       376938
                ...
Baby Bib            7
Cushion             7
Keychain            7
Leg warmers         3
Beanie              3
Name: product_type_name, Length: 105, dtype: int64

In [25]:
#product_group_name
transaction_2019summer_articles.product_group_name.value_counts()

Garment Upper body     1738012
Garment Lower body     1178308
Swimwear                777682
Garment Full body       751263
Underwear               369666
Accessories             210323
Shoes                   143697
Socks & Tights           64285
Nightwear                33708
Unknown                   6366
Bags                       357
Items                      199
Cosmetic                    81
Underwear/nightwear         61
Interior textile             7
Name: product_group_name, dtype: int64

In [26]:
#graphical_appearance_name
transaction_2019summer_articles.graphical_appearance_name.value_counts()

Solid                  2773782
All over pattern       1001964
Stripe                  381135
Denim                   295057
Melange                 152397
Lace                    122077
Other structure         108696
Placement print          80947
Dot                      53558
Front print              51047
Embroidery               50335
Check                    38414
Colour blocking          33753
Contrast                 23983
Metallic                 15103
Glittering/Metallic      14911
Jacquard                 12982
Treatment                12807
Chambray                 11397
Application/3D            8611
Mixed solid/pattern       6979
Slub                      5963
Sequin                    4486
Other pattern             3968
Neps                      3287
Transparent               3134
Unknown                   1828
Mesh                      1215
Argyle                     199
Name: graphical_appearance_name, dtype: int64

In [27]:
#colour_group_name
transaction_2019summer_articles.colour_group_name.value_counts()

Black              1642898
White               740689
Dark Blue           443280
Light Beige         227804
Light Blue          188487
Blue                179587
Off White           179269
Red                 165095
Greenish Khaki      142646
Light Pink          126502
Beige               112796
Yellow              100852
Dark Red             89080
Dark Green           87748
Dark Grey            85175
Dark Orange          82182
Grey                 81267
Light Orange         74156
Pink                 67315
Yellowish Brown      60718
Light Grey           41668
Gold                 37754
Light Yellow         35436
Orange               35262
Dark Pink            30907
Green                29234
Light Green          28014
Dark Yellow          22101
Dark Beige           21215
Turquoise            15766
Silver               14226
Light Turquoise      11358
Other Pink           10491
Dark Turquoise        7893
Light Red             6667
Other Orange          6524
Other Yellow          6004
Other                 5832
Light Purple          4386
Greyish Beige         4049
Other Red             3792
Dark Purple           3401
Purple                2988
Other Blue            2669
Other Purple          2535
Bronze/Copper         2078
Transparent           1568
Unknown               1229
Other Green           1212
Other Turquoise        210
Name: colour_group_name, dtype: int64

In [28]:
#department_name
transaction_2019summer_articles.department_name.value_counts()

Swimwear                                   751237
Blouse                                     324831
Jersey Basic                               271699
Jersey                                     269434
Trouser                                    247584
                                            ...
Accessories Boys                               31
Sneakers big girl inactive from s2             30
AK Other                                       21
Promotion/Other/Offer                          12
Underwear Jersey Fancy inactive from s1         1
Name: department_name, Length: 235, dtype: int64

In [29]:
#section_name
transaction_2019summer_articles.section_name.value_counts()

Womens Everyday Collection        1042451
Womens Swimwear, beachwear         737724
Divided Collection                 639420
Womens Lingerie                    317085
Womens Tailoring                   281319
Womens Everyday Basics             272099
Womens Casual                      234244
Divided Basics                     199322
Ladies Denim                       150485
Ladies H&M Sport                   149672
Womens Shoes                       127508
Womens Small accessories           110814
Men Underwear                      101704
Womens Trend                        98736
Womens Nightwear, Socks & Tigh      97239
H&M+                                84676
Divided Projects                    76999
Womens Big accessories              54773
Contemporary Smart                  51390
Divided Selected                    49943
Contemporary Casual                 40000
Mama                                35321
Divided Accessories                 32721
Contemporary Street                 30965
Young Girl                          25478
Denim Men                           22752
Men Suits & Tailoring               20475
Womens Jackets                      18185
Young Boy                           18165
Womens Premium                      15442
Girls Underwear & Basics            13935
Baby Essentials & Complements       13275
Kids Girl                           11037
Divided Complements Other           10994
Kids Boy                            10930
Boys Underwear & Basics              9475
Men Accessories                      9272
Kids Accessories, Swimwear & D       7750
Men H&M Sport                        6287
Men Shoes                            5538
Kids & Baby Shoes                    5239
Baby Boy                             5081
Special Collections                  5050
Divided Asia keys                    4305
Baby Girl                            4250
Collaborations                       4216
Mens Outerwear                       2690
Kids Outerwear                       2634
Kids Sports                          1769
Kids Local Relevance                 1258
Men Edition                           657
Men Project                           524
Men Other 2                           368
EQ Divided                            274
Ladies Other                           88
Men Other                              12
Name: section_name, dtype: int64

In [30]:
#garment_group_name
transaction_2019summer_articles.garment_group_name.value_counts()

Jersey Fancy                     872269
Swimwear                         765527
Jersey Basic                     537992
Dresses Ladies                   505128
Blouses                          488162
Trousers                         406889
Under-, Nightwear                398659
Shorts                           295631
Accessories                      218397
Trousers Denim                   171633
Shoes                            143182
Knitwear                         108185
Skirts                            96421
Socks and Tights                  62779
Outdoor                           49543
Unknown                           48657
Dressed                           34293
Shirts                            33079
Special Offers                    23173
Dresses/Skirts girls               8265
Woven/Jersey/Knitted mix Baby      6151
Name: garment_group_name, dtype: int64

## Subset Menswear data

In [22]:
mask = transaction_2019summer_articles.index_group_name == 'Menswear'
transaction_2019summer_menswear = transaction_2019summer_articles.loc[mask]
transaction_2019summer_menswear

,t_dat,customer_id,article_id,price,sales_channel_id,year,month,week,product_code,prod_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
60,2019-05-01,00357b192b81fc83261a45be87f5f3d59112db7d117513...,743719001,0.050831,2,2019,5,18,743719,Kate Sneaker,...,Shoes,F,Menswear,3,Menswear,27,Men Shoes,1020,Shoes,Cotton canvas trainers with a padded edge and ...
140,2019-05-01,0083ee250b3845008465de0e938d0ed2ae4f5bfde8b56e...,507431031,0.015237,2,2019,5,18,507431,Wet Tee,...,Jersey inactive from s1,F,Menswear,3,Menswear,55,Contemporary Street,1005,Jersey Fancy,T-shirt in hard-washed slub cotton jersey with...
141,2019-05-01,0083ee250b3845008465de0e938d0ed2ae4f5bfde8b56e...,378447036,0.054220,2,2019,5,18,378447,V-Neck Milan TVP,...,Knitwear,F,Menswear,3,Menswear,23,Men Suits & Tailoring,1003,Knitwear,Jumper in fine-knit merino wool with a V-neck ...
142,2019-05-01,0083ee250b3845008465de0e938d0ed2ae4f5bfde8b56e...,657850001,0.030492,2,2019,5,18,657850,KANE,...,Knitwear,F,Menswear,3,Menswear,20,Contemporary Smart,1003,Knitwear,Jumper in a textured-knit wool blend with long...
143,2019-05-01,0083ee250b3845008465de0e938d0ed2ae4f5bfde8b56e...,598755015,0.013542,2,2019,5,18,598755,Taz Tee,...,Light Basic Jersey,F,Menswear,3,Menswear,26,Men Underwear,1002,Jersey Basic,"Long, round-necked T-shirt in soft jersey with..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5273975,2019-07-31,ffc55f51a8636d9cc7b2834ae0886b1136a71a80124836...,736769005,0.006695,2,2019,7,31,736769,Parker tanktop,...,Jersey Fancy,F,Menswear,3,Menswear,21,Contemporary Casual,1005,Jersey Fancy,Vest top in cotton jersey with a print motif.
5273976,2019-07-31,ffc55f51a8636d9cc7b2834ae0886b1136a71a80124836...,736769005,0.006695,2,2019,7,31,736769,Parker tanktop,...,Jersey Fancy,F,Menswear,3,Menswear,21,Contemporary Casual,1005,Jersey Fancy,Vest top in cotton jersey with a print motif.
5273978,2019-07-31,ffc64655379797b426ef5a5be86332e901b916c1e55ab0...,663793009,0.022864,1,2019,7,31,663793,Mischa 3pk Basic,...,Underwear Jersey,F,Menswear,3,Menswear,26,Men Underwear,1017,"Under-, Nightwear",Briefs in stretch cotton jersey with flatlock ...
5273979,2019-07-31,ffc64655379797b426ef5a5be86332e901b916c1e55ab0...,501619019,0.022864,1,2019,7,31,501619,Victory voile shirt,...,Shirt,F,Menswear,3,Menswear,20,Contemporary Smart,1011,Shirts,Shirt in an airy cotton weave with a turn-down...
5274011,2019-07-31,ffe4bd3f42225fb51da4fe110a0fb2519efef670ff07ee...,757811001,0.013542,1,2019,7,31,757811,Barry Tee,...,Jersey Fancy,F,Menswear,3,Menswear,55,Contemporary Street,1005,Jersey Fancy,T-shirt in cotton jersey with a ribbed neckline.

In [ ]:
#save menswear data to csv
#transaction_2019summer_menswear.to_csv("../data/large_data/transaction_2019_567_Menswear.csv")

In [37]:
#check weekly amount of transactions
transaction_2019summer_menswear.week.value_counts().sort_index()

18    16320
19    13170
20    16647
21    18696
22    22464
23    17315
24    16619
25    29118
26    33027
27    25914
28    21961
29    20902
30    25956
31     8238
Name: week, dtype: Int64

In [38]:
#number of unique customers
transaction_2019summer_menswear.customer_id.nunique()

80081

In [39]:
transaction_2019summer_menswear.article_id.nunique()

5228

In [34]:
print(transaction_2019summer_menswear.product_group_name.value_counts())

Garment Upper body    151609
Garment Lower body     84754
Swimwear               13546
Socks & Tights         12311
Accessories             9242
Underwear               7911
Shoes                   5561
Unknown                  706
Nightwear                629
Bags                      44
Garment Full body         27
Items                      7
Name: product_group_name, dtype: int64

In [35]:
print(transaction_2019summer_menswear.section_name.value_counts())

Men Underwear            101704
Contemporary Smart        51390
Contemporary Casual       40000
Contemporary Street       30965
Denim Men                 22752
Men Suits & Tailoring     20475
Men Accessories            9272
Men Shoes                  5538
Mens Outerwear             2690
Men Edition                 657
Men Project                 524
Men Other 2                 368
Men Other                    12
Name: section_name, dtype: int64

In [40]:
print(transaction_2019summer_menswear.garment_group_name.value_counts())

Jersey Basic         67250
Jersey Fancy         55414
Shorts               43219
Shirts               30258
Trousers             17018
Swimwear             13513
Socks and Tights     12311
Trousers Denim        9727
Accessories           9294
Under-, Nightwear     8630
Knitwear              7569
Shoes                 5538
Dressed               2898
Outdoor               2804
Unknown                892
Special Offers          12
Name: garment_group_name, dtype: int64

In [30]:
print(transaction_2019summer_menswear.department_name.value_counts())

Jersey Fancy                                51540
Light Basic Jersey                          51347
Shorts                                      30194
Shirt                                       24463
Swimwear                                    13513
Trouser                                     13371
Denim shorts                                13025
Denim trousers                               9727
Heavy Basic Jersey                           8285
Knitwear                                     7403
Socks Bin                                    7248
Underwear Jersey                             6728
Shirt S&T                                    5406
Socks Wall                                   5063
Shoes                                        4632
Small Accessories                            4406
Jersey Basic                                 4214
Basics                                       3404
Trouser S&T                                  2962
Jersey inactive from s1                      2690
Accessories                                  2551
Blazer S&T                                   2320
Belts                                        1713
Underwear Woven                              1234
Jacket Smart                                 1037
Jacket Casual                                 971
Shoes / Boots inactive from s5                906
Woven inactive from s1                        685
Loungewear                                    667
Jersey License                                654
Bags & Items                                  624
Jacket Street                                 613
Blazer                                        578
On Demand                                     530
Projects                                      488
Woven                                         389
EQ H&M Man                                    287
Knitwear inactive from s1                     166
Outdoor inactive from s1                      114
Denim wardrobe H&M man inactive from S.6       81
Jacket                                         69
Local relevance                                36
Promotion/Other/Offer                          12
Underwear Jersey Fancy inactive from s1         1
Name: department_name, dtype: int64

In [29]:
mask_May = transaction_2019summer_menswear.month == 5
transaction_2019May_menswear = transaction_2019summer_menswear.loc[mask_May]
transaction_2019May_menswear

,t_dat,customer_id,article_id,price,sales_channel_id,year,month,week,product_code,prod_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
60,2019-05-01,00357b192b81fc83261a45be87f5f3d59112db7d117513...,743719001,0.050831,2,2019,5,18,743719,Kate Sneaker,...,Shoes,F,Menswear,3,Menswear,27,Men Shoes,1020,Shoes,Cotton canvas trainers with a padded edge and ...
140,2019-05-01,0083ee250b3845008465de0e938d0ed2ae4f5bfde8b56e...,507431031,0.015237,2,2019,5,18,507431,Wet Tee,...,Jersey inactive from s1,F,Menswear,3,Menswear,55,Contemporary Street,1005,Jersey Fancy,T-shirt in hard-washed slub cotton jersey with...
141,2019-05-01,0083ee250b3845008465de0e938d0ed2ae4f5bfde8b56e...,378447036,0.054220,2,2019,5,18,378447,V-Neck Milan TVP,...,Knitwear,F,Menswear,3,Menswear,23,Men Suits & Tailoring,1003,Knitwear,Jumper in fine-knit merino wool with a V-neck ...
142,2019-05-01,0083ee250b3845008465de0e938d0ed2ae4f5bfde8b56e...,657850001,0.030492,2,2019,5,18,657850,KANE,...,Knitwear,F,Menswear,3,Menswear,20,Contemporary Smart,1003,Knitwear,Jumper in a textured-knit wool blend with long...
143,2019-05-01,0083ee250b3845008465de0e938d0ed2ae4f5bfde8b56e...,598755015,0.013542,2,2019,5,18,598755,Taz Tee,...,Light Basic Jersey,F,Menswear,3,Menswear,26,Men Underwear,1002,Jersey Basic,"Long, round-necked T-shirt in soft jersey with..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1560112,2019-05-31,ff3e7a73c9f70a545e8f1b65aaf43add2a332ce40ee352...,662369024,0.027102,1,2019,5,22,662369,MAX CHECKS AND STRIPES 3PK,...,Underwear Woven,F,Menswear,3,Menswear,26,Men Underwear,1017,"Under-, Nightwear",Boxer shorts in a cotton weave with an elastic...
1560128,2019-05-31,ff4c09948c61a6362ad0d1b1d0f264f0a29b313ad11ded...,671599002,0.016932,1,2019,5,22,671599,Turner stretch polo,...,Jersey Basic,F,Menswear,3,Menswear,26,Men Underwear,1002,Jersey Basic,Short-sleeved polo shirt in soft cotton piqué ...
1560142,2019-05-31,ff594ca1a16b0a446b144953aac8dcc3b48803ea605c03...,722475008,0.025407,2,2019,5,22,722475,FRAME Easy Iron TVP,...,Shirt S&T,F,Menswear,3,Menswear,23,Men Suits & Tailoring,1011,Shirts,Long-sleeved shirt in woven fabric with an eas...
1560144,2019-05-31,ff5e6659ef28d55d17bf5ee8d7071658e848d3ddc3439c...,570002054,0.013542,1,2019,5,22,570002,R-NECK SS SLIM FIT,...,Light Basic Jersey,F,Menswear,3,Menswear,26,Men Underwear,1002,Jersey Basic,Round-necked T-shirt in soft jersey.
1560217,2019-05-31,ff9243c85f22d8842e787f5d2a62657537ae4bca134e92...,699923038,0.010153,1,2019,5,22,699923,Mike tee,...,Jersey Fancy,F,Menswear,3,Menswear,21,Contemporary Casual,1005,Jersey Fancy,"T-shirt in soft, printed cotton jersey."

In [32]:
mask_July = transaction_2019summer_menswear.month == 7
transaction_2019July_menswear = transaction_2019summer_menswear.loc[mask_July]
transaction_2019July_menswear

,t_dat,customer_id,article_id,price,sales_channel_id,year,month,week,product_code,prod_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
3466550,2019-07-01,0024dea548c64fb75a563e0b300c0b16210decee446f1a...,570002054,0.013542,1,2019,7,27,570002,R-NECK SS SLIM FIT,...,Light Basic Jersey,F,Menswear,3,Menswear,26,Men Underwear,1002,Jersey Basic,Round-necked T-shirt in soft jersey.
3466551,2019-07-01,0024dea548c64fb75a563e0b300c0b16210decee446f1a...,570002048,0.013542,1,2019,7,27,570002,R-NECK SS SLIM FIT,...,Light Basic Jersey,F,Menswear,3,Menswear,26,Men Underwear,1002,Jersey Basic,Round-necked T-shirt in soft jersey.
3466553,2019-07-01,0024dea548c64fb75a563e0b300c0b16210decee446f1a...,570002007,0.013542,1,2019,7,27,570002,R-NECK SS SLIM FIT,...,Light Basic Jersey,F,Menswear,3,Menswear,26,Men Underwear,1002,Jersey Basic,Round-necked T-shirt in soft jersey.
3466567,2019-07-01,003dcdb1164332b8ac9b1698861fc2a423f202d7df51df...,567438007,0.084729,2,2019,7,27,567438,Clark Slim Trs,...,Trouser,F,Menswear,3,Menswear,23,Men Suits & Tailoring,1009,Trousers,Suit trousers in marled Italian wool with stit...
3466570,2019-07-01,003dcdb1164332b8ac9b1698861fc2a423f202d7df51df...,764151002,0.059305,2,2019,7,27,764151,Elvis skinny cropped trs,...,Trouser,F,Menswear,3,Menswear,23,Men Suits & Tailoring,1009,Trousers,Ankle-length suit trousers in a stretch weave ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5273975,2019-07-31,ffc55f51a8636d9cc7b2834ae0886b1136a71a80124836...,736769005,0.006695,2,2019,7,31,736769,Parker tanktop,...,Jersey Fancy,F,Menswear,3,Menswear,21,Contemporary Casual,1005,Jersey Fancy,Vest top in cotton jersey with a print motif.
5273976,2019-07-31,ffc55f51a8636d9cc7b2834ae0886b1136a71a80124836...,736769005,0.006695,2,2019,7,31,736769,Parker tanktop,...,Jersey Fancy,F,Menswear,3,Menswear,21,Contemporary Casual,1005,Jersey Fancy,Vest top in cotton jersey with a print motif.
5273978,2019-07-31,ffc64655379797b426ef5a5be86332e901b916c1e55ab0...,663793009,0.022864,1,2019,7,31,663793,Mischa 3pk Basic,...,Underwear Jersey,F,Menswear,3,Menswear,26,Men Underwear,1017,"Under-, Nightwear",Briefs in stretch cotton jersey with flatlock ...
5273979,2019-07-31,ffc64655379797b426ef5a5be86332e901b916c1e55ab0...,501619019,0.022864,1,2019,7,31,501619,Victory voile shirt,...,Shirt,F,Menswear,3,Menswear,20,Contemporary Smart,1011,Shirts,Shirt in an airy cotton weave with a turn-down...
5274011,2019-07-31,ffe4bd3f42225fb51da4fe110a0fb2519efef670ff07ee...,757811001,0.013542,1,2019,7,31,757811,Barry Tee,...,Jersey Fancy,F,Menswear,3,Menswear,55,Contemporary Street,1005,Jersey Fancy,T-shirt in cotton jersey with a ribbed neckline.

In [31]:
print(transaction_2019May_menswear.department_name.value_counts())

Light Basic Jersey                          13456
Jersey Fancy                                11991
Shirt                                        7678
Shorts                                       7359
Trouser                                      4158
Heavy Basic Jersey                           3520
Denim trousers                               3498
Swimwear                                     3255
Knitwear                                     2682
Socks Bin                                    2205
Denim shorts                                 2077
Underwear Jersey                             1984
Shirt S&T                                    1884
Socks Wall                                   1838
Small Accessories                            1338
Trouser S&T                                  1269
Jersey Basic                                 1165
Blazer S&T                                   1086
Shoes                                        1067
Basics                                        943
Jersey inactive from s1                       818
Belts                                         614
Accessories                                   600
Jacket Smart                                  471
Jacket Casual                                 456
Underwear Woven                               310
Shoes / Boots inactive from s5                242
Jacket Street                                 238
Loungewear                                    224
Woven inactive from s1                        221
Blazer                                        212
Projects                                      180
Jersey License                                159
Bags & Items                                  135
Woven                                         105
On Demand                                      96
Knitwear inactive from s1                      77
EQ H&M Man                                     59
Outdoor inactive from s1                       59
Jacket                                         56
Denim wardrobe H&M man inactive from S.6       32
Local relevance                                11
Underwear Jersey Fancy inactive from s1         1
Name: department_name, dtype: int64

In [33]:
print(transaction_2019July_menswear.department_name.value_counts())

Jersey Fancy                                19454
Light Basic Jersey                          17953
Shorts                                      11084
Shirt                                        7991
Denim shorts                                 6170
Swimwear                                     5176
Trouser                                      4628
Denim trousers                               3311
Heavy Basic Jersey                           2934
Underwear Jersey                             2542
Socks Bin                                    2415
Knitwear                                     2408
Shoes                                        1985
Shirt S&T                                    1709
Jersey Basic                                 1678
Socks Wall                                   1653
Small Accessories                            1530
Basics                                       1336
Accessories                                  1017
Trouser S&T                                   779
Jersey inactive from s1                       750
Underwear Woven                               527
Belts                                         521
Blazer S&T                                    520
Shoes / Boots inactive from s5                307
On Demand                                     291
Jacket Casual                                 250
Jersey License                                249
Jacket Smart                                  245
Bags & Items                                  239
Loungewear                                    223
Jacket Street                                 214
Projects                                      191
Woven inactive from s1                        178
Blazer                                        157
Woven                                         145
EQ H&M Man                                    117
Denim wardrobe H&M man inactive from S.6       27
Knitwear inactive from s1                      27
Outdoor inactive from s1                       15
Local relevance                                11
Promotion/Other/Offer                          11
Jacket                                          3
Name: department_name, dtype: int64

In [11]:
## Consine similarity vs. euclidean distance
import numpy as np
from sklearn.metrics.pairwise import euclidean_distances, cosine_similarity

m = np.array([[0,0.2,0],
              [0,0.8,0]])

print(euclidean_distances(m, m))
print(cosine_similarity(m))

[[0.  0.6]
 [0.6 0. ]]
[[1. 1.]
 [1. 1.]]